# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-03 10:32
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id_article', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id_article', models.PositiveIntegerField(serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateField(verbose_name=datetime.datetime(2020, 2, 3, 10, 32, 56, 404533))),
                ('updated_at', models.DateField(null=True)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('is_visible_for_quests', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_visible_for_quests', models.BooleanField(default=True)),
                ('include_in_menu', models.BooleanField(default=True)),
                ('parent_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id_model', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateField(verbose_name=datetime.datetime(2020, 2, 3, 10, 32, 56, 405404))),
                ('updated_at', models.DateField(null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id_rating', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=75)),
                ('email', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateField(verbose_name=datetime.datetime(2020, 2, 3, 10, 32, 56, 403383))),
                ('updated_at', models.DateField(null=True)),
                ('last_login_at', models.DateField(null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('auth_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.User'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.User'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='parent_article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Article'),
        ),
    ]
