# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-03 10:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateField(verbose_name=datetime.datetime(2020, 2, 3, 10, 37, 9, 768266)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateField(verbose_name=datetime.datetime(2020, 2, 3, 10, 37, 9, 769617)),
        ),
    ]
